% This file contains the structure used to save the results of the
% predictive simulations and is loaded in the different files that are 
% processing and analyzing the results

v_tgt       = settings(ww(k),1);    % average speed
tol_ipopt   = settings(ww(k),2);    % tolerance (means 1e-(tol_ipopt))
N           = settings(ww(k),3);    % number of mesh intervals
W.E         = settings(ww(k),4);    % weight metabolic energy
W.Ak        = settings(ww(k),5);    % weight joint accelerations
W.ArmE      = settings(ww(k),6);    % weight arm excitations
W.passMom   = settings(ww(k),7);    % weight passive torques
W.A         = settings(ww(k),8);    % weight muscle activations
exp_E       = settings(ww(k),9);    % power metabolic energy
IGsel       = settings(ww(k),10);   % initial guess identifier
cm          = settings(ww(k),11);   % contact model identifier
IGm         = settings(ww(k),12);   % initial guess mode identifier
IGcase      = settings(ww(k),13);   % initial guess case identifier
h_weak      = settings(ww(k),14);   % weakness hip actuators
vMax_s      = settings(ww(k),15);   % maximal contraction velocity identifier
pf_weak     = settings(ww(k),16);   % weakness ankle plantaflexors
mE          = settings(ww(k),17);   % metabolic energy model identifier
coCont      = settings(ww(k),18);   % co-contraction identifier

% load results
pathmain = pwd;
[pathrepo,~,~] = fileparts(pathmain);
pathresults = [pathrepo,'/Results/PredSim_all_opti_int_NLPSol_order_par_mtp'];
load([pathresults,'/Results_all_opti_int_NLPSol_order_par.mat']);
v_tgt_id = round(v_tgt,2);

Qs_opt(ww(k)).m = Results_all.(['Speed_',num2str(v_tgt_id*100)]). ...  
        (['W_MetabolicEnergyRate_',num2str(W.E)]). ...
        (['W_MuscleActivity_',num2str(W.A)]). ...            
        (['W_JointAcceleration_',num2str(W.Ak)]). ...
        (['W_PassiveTorque_',num2str(W.passMom)]). ...
        (['W_ArmExcitation_',num2str(W.ArmE)]). ...               
        (['Power_MetabolicEnergyRate_',num2str(exp_E)]). ...
        (['InitialGuessType_',num2str(IGsel)]). ...
        (['InitialGuessMode_',num2str(IGm)]). ...
        (['InitialGuessCase_',num2str(IGcase)]). ... 
        (['WeaknessHipActuators_',num2str(h_weak)]). ...
        (['WeaknessAnklePlantarflexors_',num2str(pf_weak)]). ...   
        (['MetabolicEnergyModel_',num2str(mE)]). ...            
        (['ContactModel_',num2str(cm)]). ...  
        (['Number_MeshIntervals_',num2str(N)]). ...
        (['MaximumContractionVelocity_',num2str(vMax_s)]). ...
        (['CoContraction_',num2str(coCont)]).Qs_opt;
Qdots_opt(ww(k)).m = Results_all.(['Speed_',num2str(v_tgt_id*100)]). ...  
        (['W_MetabolicEnergyRate_',num2str(W.E)]). ...
        (['W_MuscleActivity_',num2str(W.A)]). ...            
        (['W_JointAcceleration_',num2str(W.Ak)]). ...
        (['W_PassiveTorque_',num2str(W.passMom)]). ...
        (['W_ArmExcitation_',num2str(W.ArmE)]). ...               
        (['Power_MetabolicEnergyRate_',num2str(exp_E)]). ...
        (['InitialGuessType_',num2str(IGsel)]). ...
        (['InitialGuessMode_',num2str(IGm)]). ...
        (['InitialGuessCase_',num2str(IGcase)]). ... 
        (['WeaknessHipActuators_',num2str(h_weak)]). ...
        (['WeaknessAnklePlantarflexors_',num2str(pf_weak)]). ...   
        (['MetabolicEnergyModel_',num2str(mE)]). ...            
        (['ContactModel_',num2str(cm)]). ...  
        (['Number_MeshIntervals_',num2str(N)]). ...
        (['MaximumContractionVelocity_',num2str(vMax_s)]). ...
        (['CoContraction_',num2str(coCont)]).Qdots_opt;
Acts_opt(ww(k)).m = Results_all.(['Speed_',num2str(v_tgt_id*100)]). ...  
        (['W_MetabolicEnergyRate_',num2str(W.E)]). ...
        (['W_MuscleActivity_',num2str(W.A)]). ...            
        (['W_JointAcceleration_',num2str(W.Ak)]). ...
        (['W_PassiveTorque_',num2str(W.passMom)]). ...
        (['W_ArmExcitation_',num2str(W.ArmE)]). ...               
        (['Power_MetabolicEnergyRate_',num2str(exp_E)]). ...
        (['InitialGuessType_',num2str(IGsel)]). ...
        (['InitialGuessMode_',num2str(IGm)]). ...
        (['InitialGuessCase_',num2str(IGcase)]). ... 
        (['WeaknessHipActuators_',num2str(h_weak)]). ...
        (['WeaknessAnklePlantarflexors_',num2str(pf_weak)]). ...   
        (['MetabolicEnergyModel_',num2str(mE)]). ...            
        (['ContactModel_',num2str(cm)]). ...  
        (['Number_MeshIntervals_',num2str(N)]). ...
        (['MaximumContractionVelocity_',num2str(vMax_s)]). ...
        (['CoContraction_',num2str(coCont)]).Acts_opt;
Ts_opt(ww(k)).m = Results_all.(['Speed_',num2str(v_tgt_id*100)]). ...  
        (['W_MetabolicEnergyRate_',num2str(W.E)]). ...
        (['W_MuscleActivity_',num2str(W.A)]). ...            
        (['W_JointAcceleration_',num2str(W.Ak)]). ...
        (['W_PassiveTorque_',num2str(W.passMom)]). ...
        (['W_ArmExcitation_',num2str(W.ArmE)]). ...               
        (['Power_MetabolicEnergyRate_',num2str(exp_E)]). ...
        (['InitialGuessType_',num2str(IGsel)]). ...
        (['InitialGuessMode_',num2str(IGm)]). ...
        (['InitialGuessCase_',num2str(IGcase)]). ... 
        (['WeaknessHipActuators_',num2str(h_weak)]). ...
        (['WeaknessAnklePlantarflexors_',num2str(pf_weak)]). ...   
        (['MetabolicEnergyModel_',num2str(mE)]). ...            
        (['ContactModel_',num2str(cm)]). ...  
        (['Number_MeshIntervals_',num2str(N)]). ...
        (['MaximumContractionVelocity_',num2str(vMax_s)]). ...
        (['CoContraction_',num2str(coCont)]).Ts_opt;
GRFs_opt(ww(k)).m = Results_all.(['Speed_',num2str(v_tgt_id*100)]). ...  
        (['W_MetabolicEnergyRate_',num2str(W.E)]). ...
        (['W_MuscleActivity_',num2str(W.A)]). ...            
        (['W_JointAcceleration_',num2str(W.Ak)]). ...
        (['W_PassiveTorque_',num2str(W.passMom)]). ...
        (['W_ArmExcitation_',num2str(W.ArmE)]). ...               
        (['Power_MetabolicEnergyRate_',num2str(exp_E)]). ...
        (['InitialGuessType_',num2str(IGsel)]). ...
        (['InitialGuessMode_',num2str(IGm)]). ...
        (['InitialGuessCase_',num2str(IGcase)]). ... 
        (['WeaknessHipActuators_',num2str(h_weak)]). ...
        (['WeaknessAnklePlantarflexors_',num2str(pf_weak)]). ...   
        (['MetabolicEnergyModel_',num2str(mE)]). ...            
        (['ContactModel_',num2str(cm)]). ...  
        (['Number_MeshIntervals_',num2str(N)]). ...
        (['MaximumContractionVelocity_',num2str(vMax_s)]). ...
        (['CoContraction_',num2str(coCont)]).GRFs_opt;
COT_opt(ww(k)).m = Results_all.(['Speed_',num2str(v_tgt_id*100)]). ...  
        (['W_MetabolicEnergyRate_',num2str(W.E)]). ...
        (['W_MuscleActivity_',num2str(W.A)]). ...            
        (['W_JointAcceleration_',num2str(W.Ak)]). ...
        (['W_PassiveTorque_',num2str(W.passMom)]). ...
        (['W_ArmExcitation_',num2str(W.ArmE)]). ...               
        (['Power_MetabolicEnergyRate_',num2str(exp_E)]). ...
        (['InitialGuessType_',num2str(IGsel)]). ...
        (['InitialGuessMode_',num2str(IGm)]). ...
        (['InitialGuessCase_',num2str(IGcase)]). ... 
        (['WeaknessHipActuators_',num2str(h_weak)]). ...
        (['WeaknessAnklePlantarflexors_',num2str(pf_weak)]). ...   
        (['MetabolicEnergyModel_',num2str(mE)]). ...            
        (['ContactModel_',num2str(cm)]). ...  
        (['Number_MeshIntervals_',num2str(N)]). ...
        (['MaximumContractionVelocity_',num2str(vMax_s)]). ...
        (['CoContraction_',num2str(coCont)]).COT_opt;
StrideLength_opt(ww(k)).m = Results_all.(['Speed_',num2str(v_tgt_id*100)]). ...  
        (['W_MetabolicEnergyRate_',num2str(W.E)]). ...
        (['W_MuscleActivity_',num2str(W.A)]). ...            
        (['W_JointAcceleration_',num2str(W.Ak)]). ...
        (['W_PassiveTorque_',num2str(W.passMom)]). ...
        (['W_ArmExcitation_',num2str(W.ArmE)]). ...               
        (['Power_MetabolicEnergyRate_',num2str(exp_E)]). ...
        (['InitialGuessType_',num2str(IGsel)]). ...
        (['InitialGuessMode_',num2str(IGm)]). ...
        (['InitialGuessCase_',num2str(IGcase)]). ... 
        (['WeaknessHipActuators_',num2str(h_weak)]). ...
        (['WeaknessAnklePlantarflexors_',num2str(pf_weak)]). ...   
        (['MetabolicEnergyModel_',num2str(mE)]). ...            
        (['ContactModel_',num2str(cm)]). ...  
        (['Number_MeshIntervals_',num2str(N)]). ...
        (['MaximumContractionVelocity_',num2str(vMax_s)]). ...
        (['CoContraction_',num2str(coCont)]).StrideLength_opt;
StepWidth_opt(ww(k)).m = Results_all.(['Speed_',num2str(v_tgt_id*100)]). ...  
        (['W_MetabolicEnergyRate_',num2str(W.E)]). ...
        (['W_MuscleActivity_',num2str(W.A)]). ...            
        (['W_JointAcceleration_',num2str(W.Ak)]). ...
        (['W_PassiveTorque_',num2str(W.passMom)]). ...
        (['W_ArmExcitation_',num2str(W.ArmE)]). ...               
        (['Power_MetabolicEnergyRate_',num2str(exp_E)]). ...
        (['InitialGuessType_',num2str(IGsel)]). ...
        (['InitialGuessMode_',num2str(IGm)]). ...
        (['InitialGuessCase_',num2str(IGcase)]). ... 
        (['WeaknessHipActuators_',num2str(h_weak)]). ...
        (['WeaknessAnklePlantarflexors_',num2str(pf_weak)]). ...   
        (['MetabolicEnergyModel_',num2str(mE)]). ...            
        (['ContactModel_',num2str(cm)]). ...  
        (['Number_MeshIntervals_',num2str(N)]). ...
        (['MaximumContractionVelocity_',num2str(vMax_s)]). ...
        (['CoContraction_',num2str(coCont)]).StepWidth_opt;
    